#
# YAML Configuration File - app.local
#     Application Configuration File for Local Context
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

# NOTE: because default is loaded from app.yml, omit duplicates and write
#       overwrite entries.
---

app:
  debug: true

routing:
  caching: false

...