#
# YAML Configuration File - routing
#     Routing for the application goes here
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---

home:
  rewrite: "/"
  method: "get"
  actual: "packfire.welcome.HomeController"

themeSwitch:
  rewrite: "/theme/switch/{theme}"
  actual: "packfire.welcome.ThemeSwitchController"
  params:
    theme: "([a-zA-Z0-9]+)"
  
...